version: '3.9'
services:
  db:
    image: postgres:16
    container_name: phishnet_db
    environment:
      POSTGRES_USER: phishnet
      POSTGRES_PASSWORD: phishnet
      POSTGRES_DB: phishnet_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phishnet"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  # mail:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - "8025:8025"

  # cache:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"

volumes:
  db_data: {}