name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.cjs