name: Docs Validation

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'docusaurus.config.*'
      - 'sidebars.*'
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Docs validation steps (markdown lint, links) to be added later"