name: Feature Flag Expiry Check

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "feature flag expiry scan placeholder"