name: TODO/FIXME Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "scan for TODO/FIXME without Jira key placeholder"